/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 *
 * @author pc
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        seven = new javax.swing.JButton();
        six = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        square = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        five = new javax.swing.JButton();
        three = new javax.swing.JButton();
        two = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        four = new javax.swing.JButton();
        answer = new javax.swing.JButton();
        one = new javax.swing.JButton();
        cube = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        subtraction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Calculator");

        result.setForeground(new java.awt.Color(204, 0, 51));
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        seven.setBackground(java.awt.Color.cyan);
        seven.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        seven.setText("7");
        seven.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        six.setBackground(java.awt.Color.cyan);
        six.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        six.setText("6");
        six.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        eight.setBackground(java.awt.Color.cyan);
        eight.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        eight.setText("8");
        eight.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        square.setBackground(java.awt.Color.cyan);
        square.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        square.setText("x²");
        square.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });

        nine.setBackground(java.awt.Color.cyan);
        nine.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nine.setText("9");
        nine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        clear.setBackground(java.awt.Color.cyan);
        clear.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        clear.setText("C");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        dot.setBackground(java.awt.Color.cyan);
        dot.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        dot.setText(".");
        dot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        five.setBackground(java.awt.Color.cyan);
        five.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        five.setText("5");
        five.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        three.setBackground(java.awt.Color.cyan);
        three.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        three.setText("3");
        three.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        two.setBackground(java.awt.Color.cyan);
        two.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        two.setText("2");
        two.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        zero.setBackground(java.awt.Color.cyan);
        zero.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        zero.setText("0");
        zero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        four.setBackground(java.awt.Color.cyan);
        four.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        four.setText("4");
        four.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        answer.setBackground(java.awt.Color.cyan);
        answer.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        answer.setText("=");
        answer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });

        one.setBackground(java.awt.Color.cyan);
        one.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        one.setText("1");
        one.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        cube.setBackground(java.awt.Color.cyan);
        cube.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        cube.setText(" x³ ");
        cube.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeActionPerformed(evt);
            }
        });

        divide.setBackground(java.awt.Color.cyan);
        divide.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        divide.setText("/");
        divide.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        multiply.setBackground(java.awt.Color.cyan);
        multiply.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        multiply.setText("X");
        multiply.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        sum.setBackground(java.awt.Color.cyan);
        sum.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        sum.setText("+");
        sum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        subtraction.setBackground(java.awt.Color.cyan);
        subtraction.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        subtraction.setText("-");
        subtraction.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(two, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtraction, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(multiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(six, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(square, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cube, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cube, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(sum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
       
    }//GEN-LAST:event_resultActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
       //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="1";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_oneActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
         //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="0";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
      
    }//GEN-LAST:event_zeroActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
     
         //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="2";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
        
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="3";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
     
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
      //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="4";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_fourActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
         //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="7";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
   //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="8";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
         //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="9";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_nineActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
         //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="6";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_sixActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
         //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="5";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_fiveActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
      //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b=".";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_dotActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
         //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="+";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_sumActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
       //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="/";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_divideActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="*";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_multiplyActionPerformed

    private void subtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionActionPerformed
 //storing data in variable a from the text field
        String a=result.getText();
       //storing the value in the b as 3
         String b="-";
         /*displaying the value with concatination as it will give output as 4+5+8/3*5 in text area
         logic behind this is at first it takes the data in textfield which was store in a variable and 
         and it set to display combinig the data two i.e concating the two data for eg
         let us assume the value of a is 1 which was fetch from the textfield 
         and acutally value of this button of b is 2 now when clicked button it will appeared 12
         */
         result.setText(a+b);
    }//GEN-LAST:event_subtractionActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        //storing the String from the textarea
        String a=result.getText();
        //converting the string into integer value
        int b=Integer.valueOf(a);
        //muliplying the both by same integer value twice that is b
        int c=b*b;
        //printing the value in the text area
        result.setText(String.valueOf(c));
    }//GEN-LAST:event_squareActionPerformed

    private void cubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeActionPerformed
     //storing the String from the textarea
        String a=result.getText();
        //converting the string into integer value
     int b=Integer.valueOf(a);
       //muliplying the both by same integer value thrice that is b
     int c=b*b*b;
      //printing the value in the text area
     result.setText(String.valueOf(c));
    }//GEN-LAST:event_cubeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        //clearing the text field and setting for new setup
        result.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
       //getting the text from the text area
        String a=result.getText();
       try{
        //this interface can cause excepion
        //creaing new inerface
        ScriptEngineManager manager = new ScriptEngineManager();
        //importing js method 
        ScriptEngine engine = manager.getEngineByName("js");
        //evaluating the text got from the textarea      
        Object ans =String.valueOf(engine.eval(a)); 
       //printing the result
        result.setText(String.valueOf(ans));  
        System.out.println(ans);
       }
       catch(ScriptException e){
           
       }
    }//GEN-LAST:event_answerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answer;
    private javax.swing.JButton clear;
    private javax.swing.JButton cube;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JTextField result;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton square;
    private javax.swing.JButton subtraction;
    private javax.swing.JButton sum;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
